<a href="https://colab.research.google.com/github/mashan275/data-science-2024/blob/main/Pertemuan2_Hasta_satriya_240401010207.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# =========================================
# PYTHON DASAR + NUMPY + PANDAS
# =========================================

# =========================================
# LIST
# =========================================

print("\n===== LIST =====")

# Membuat list
data = [10, 20, 'Python', True, 3.14]

# Akses & slicing
print(data[0])      # → 10
print(data[-1])     # → 3.14
print(data[1:3])    # → [20, 'Python']

# Manipulasi
data.append(99)
data.insert(1, 55)
data.remove(20)

print("List akhir:", data)

# =========================================
# DICTIONARY
# =========================================

print("\n===== DICTIONARY =====")

mahasiswa = {
    'nama': 'Hasta Satriya',
    'nim': '240401010207',
    'prodi': 'Informatika',
    'ipk': 3.94
}

# Akses nilai
print(mahasiswa['nama'])
print(mahasiswa.get('usia', 32))

# Update dan hapus
mahasiswa['angkatan'] = 2024
del mahasiswa['nim']

print("Dictionary akhir:", mahasiswa)

# =========================================
# NUMPY
# =========================================

print("\n===== NUMPY =====")

import numpy as np

# Array 1D dan 2D
a1D = np.array([1, 2, 3, 4, 5])
a2D = np.array([[1, 2, 3], [4, 5, 6]])

print("Array 1D:")
print(a1D)

print("\nArray 2D:")
print(a2D)

# Array inisial
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
eye = np.eye(4)
full = np.full((2, 2), 7)

print("\nZeros:")
print(zeros)

print("\nOnes:")
print(ones)

print("\nIdentity Matrix:")
print(eye)

print("\nFull Array:")
print(full)

# Sequence
arange = np.arange(0, 20, 2)
linsp = np.linspace(0, 1, 11)

print("\nArange:")
print(arange)

print("\nLinspace:")
print(linsp)

# Random generator
rng = np.random.default_rng(seed=42)

rand_int = rng.integers(0, 100, (3, 4))
rand_flt = rng.normal(loc=0, scale=1, size=(10,))

print("\nRandom Integer:")
print(rand_int)

print("\nRandom Float:")
print(rand_flt)

# =========================================
# OPERASI ARRAY
# =========================================

print("\n===== OPERASI ARRAY =====")

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("a + b =", a + b)
print("a * b =", a * b)
print("a ** 2 =", a ** 2)

# Universal functions
print("\nSqrt(a):")
print(np.sqrt(a))

print("\nExp(a):")
print(np.exp(a))

print("\nLog(b):")
print(np.log(b))

# =========================================
# STATISTIK NUMPY
# =========================================

print("\n===== STATISTIK NUMPY =====")

data_stat = rng.normal(0, 1, 1000)

print(f"Mean : {np.mean(data_stat):.4f}")
print(f"Std  : {np.std(data_stat):.4f}")
print(f"Min  : {np.min(data_stat):.4f}")
print(f"Max  : {np.max(data_stat):.4f}")
print(f"Q1   : {np.percentile(data_stat, 25):.4f}")
print(f"Q3   : {np.percentile(data_stat, 75):.4f}")

# =========================================
# PANDAS SERIES
# =========================================

print("\n===== PANDAS SERIES =====")

import pandas as pd

# Series default index
s1 = pd.Series([85, 92, 78, 95, 88])

print("\nSeries s1:")
print(s1)

# Series custom index
nilai = pd.Series(
    [85, 92, 78, 95],
    index=['Alice', 'Bob', 'Caca', 'Dina']
)

print("\nNilai Bob:")
print(nilai['Bob'])

print("\nNilai > 80:")
print(nilai[nilai > 80])

print("\nRata-rata:")
print(nilai.mean())

print("\nDescribe:")
print(nilai.describe())

# =========================================
# DATAFRAME
# =========================================

print("\n===== DATAFRAME =====")

data_df = {
    'nama': ['Ali', 'Hasta', 'Caca', 'Dina'],
    'usia': [22, 25, 21, 23],
    'kota': ['Jakarta', 'Bandung', 'Surabaya', 'Medan'],
    'ipk': [3.8, 3.5, 3.9, 3.7]
}

df = pd.DataFrame(data_df)

print("\nDataFrame:")
print(df)

print("\nShape:")
print(df.shape)

print("\nDtypes:")
print(df.dtypes)

print("\nColumns:")
print(df.columns)

# =========================================
# SIMPAN & BACA CSV
# =========================================

print("\n===== CSV =====")

# Simpan ke CSV
df.to_csv('data_mahasiswa.csv', index=False)

# Baca CSV
df_csv = pd.read_csv('data_mahasiswa.csv')

print("\nData dari CSV:")
print(df_csv)

# =========================================
# FILTERING DATAFRAME
# =========================================

print("\n===== FILTERING =====")

# Filter IPK > 3.7
ipk_tinggi = df[df['ipk'] > 3.7]

print("\nMahasiswa IPK > 3.7:")
print(ipk_tinggi)

# Filter kota tertentu
jakarta = df[df['kota'] == 'Jakarta']

print("\nMahasiswa dari Jakarta:")
print(jakarta)

# Pilih kolom tertentu
print("\nKolom tertentu:")
print(df[['nama', 'ipk']])

# =========================================
# GROUPBY & AGGREGATION
# =========================================

print("\n===== GROUPBY =====")

# Tambah kolom kategori
df['kategori'] = ['A', 'B', 'A', 'B']

hasil = df.groupby('kategori').agg(
    jumlah=('nama', 'count'),
    rata_ipk=('ipk', 'mean'),
    max_ipk=('ipk', 'max')
)

print("\nHasil GroupBy:")
print(hasil.round(2))

# =========================================
# SELESAI
# =========================================

print("\n===== PROGRAM SELESAI =====")


===== LIST =====
10
3.14
[20, 'Python']
List akhir: [10, 55, 'Python', True, 3.14, 99]

===== DICTIONARY =====
Hasta Satriya
32
Dictionary akhir: {'nama': 'Hasta Satriya', 'prodi': 'Informatika', 'ipk': 3.94, 'angkatan': 2024}

===== NUMPY =====
Array 1D:
[1 2 3 4 5]

Array 2D:
[[1 2 3]
 [4 5 6]]

Zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Full Array:
[[7 7]
 [7 7]]

Arange:
[ 0  2  4  6  8 10 12 14 16 18]

Linspace:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

Random Integer:
[[ 8 77 65 43]
 [43 85  8 69]
 [20  9 52 97]]

Random Float:
[ 0.1278404  -0.31624259 -0.01680116 -0.85304393  0.87939797  0.77779194
  0.0660307   1.12724121  0.46750934 -0.85929246]

===== OPERASI ARRAY =====
a + b = [11 22 33 44 55]
a * b = [ 10  40  90 160 250]
a ** 2 = [ 1  4  9 16 25]

Sqrt(a):
[1.         1.41421356 1.73205081 2.         2.23606798]

Exp(a):
[  2.71828183   7.3890561

In [4]:
# =========================================================
# PERTEMUAN 2
# Struktur Data Python, NumPy & Pandas
# Studi Kasus: Dataset Titanic
# =========================================================

# =========================================================
# SECTION 1
# IMPORT LIBRARY
# =========================================================

import pandas as pd
import numpy as np

# =========================================================
# SECTION 2
# LOAD DATASET TITANIC
# =========================================================

# URL dataset Titanic
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

# Membaca dataset
df = pd.read_csv(url)

# Menampilkan 5 data pertama
print("===== DATA TITANIC =====")
print(df.head())

# =========================================================
# Q1
# Berapa jumlah baris dan kolom pada dataset Titanic?
# Kolom apa saja yang tersedia?
# =========================================================

print("\n===== Q1 =====")

# Shape dataset
jumlah_baris, jumlah_kolom = df.shape

print(f"Jumlah baris : {jumlah_baris}")
print(f"Jumlah kolom : {jumlah_kolom}")

# Menampilkan nama kolom
print("\nDaftar Kolom:")
print(df.columns.tolist())

# ---------------------------------------------------------
# Penjelasan:
# Dataset Titanic memiliki sejumlah baris data penumpang
# dan beberapa kolom informasi seperti umur, jenis kelamin,
# kelas penumpang, harga tiket, dan status keselamatan.
# ---------------------------------------------------------

# =========================================================
# Q2
# Kolom mana saja yang memiliki missing values?
# Berapa jumlah dan proporsinya (%)?
# =========================================================

print("\n===== Q2 =====")

# Menghitung missing values
missing = df.isnull().sum()

# Menghitung persentase missing
missing_percent = (missing / len(df)) * 100

# Membuat DataFrame ringkasan
missing_df = pd.DataFrame({
    'Jumlah Missing': missing,
    'Persentase (%)': missing_percent.round(2)
})

# Filter hanya kolom yang memiliki missing value
missing_df = missing_df[missing_df['Jumlah Missing'] > 0]

print(missing_df)

# ---------------------------------------------------------
# Penjelasan:
# Beberapa kolom memiliki data kosong (missing values),
# terutama kolom Cabin, Age, dan Embarked.
# Cabin memiliki missing value paling banyak.
# ---------------------------------------------------------

# =========================================================
# Q3
# Berapa persen penumpang yang selamat?
# =========================================================

print("\n===== Q3 =====")

# Mean dari Survived
persen_selamat = df['Survived'].mean() * 100

print(f"Persentase penumpang selamat: {persen_selamat:.2f}%")

# ---------------------------------------------------------
# Penjelasan:
# Nilai Survived:
# 1 = selamat
# 0 = tidak selamat
#
# Karena data berbentuk biner, rata-rata kolom Survived
# langsung merepresentasikan proporsi penumpang selamat.
# ---------------------------------------------------------

# =========================================================
# Q4
# Filter penumpang wanita dari kelas 1
# Berapa jumlah dan rata-rata usianya?
# =========================================================

print("\n===== Q4 =====")

# Filter wanita kelas 1
wanita_kelas1 = df[
    (df['Sex'] == 'female') &
    (df['Pclass'] == 1)
]

# Jumlah penumpang
jumlah_wanita_kelas1 = wanita_kelas1.shape[0]

# Rata-rata usia
rata_usia = wanita_kelas1['Age'].mean()

print(f"Jumlah wanita kelas 1 : {jumlah_wanita_kelas1}")
print(f"Rata-rata usia        : {rata_usia:.2f}")

# ---------------------------------------------------------
# Penjelasan:
# Penumpang wanita kelas 1 merupakan kelompok dengan
# fasilitas terbaik pada kapal Titanic.
# Analisis ini menunjukkan jumlah serta rata-rata usia
# kelompok tersebut.
# ---------------------------------------------------------

# =========================================================
# Q5
# Hitung tingkat keselamatan per kelas penumpang
# =========================================================

print("\n===== Q5 =====")

# GroupBy tingkat keselamatan
survival_per_class = df.groupby('Pclass')['Survived'].mean()

print(survival_per_class)

# Menentukan kelas dengan survival tertinggi
kelas_tertinggi = survival_per_class.idxmax()
nilai_tertinggi = survival_per_class.max()

print(f"\nKelas dengan survival tertinggi: {kelas_tertinggi}")
print(f"Tingkat survival: {nilai_tertinggi:.2%}")

# ---------------------------------------------------------
# Penjelasan:
# Penumpang kelas 1 memiliki tingkat keselamatan tertinggi.
# Hal ini menunjukkan adanya pengaruh kelas sosial terhadap
# peluang keselamatan pada tragedi Titanic.
# ---------------------------------------------------------

# =========================================================
# Q6
# Analisis tambahan
# Analisis tingkat keselamatan berdasarkan jenis kelamin
# =========================================================

print("\n===== Q6 =====")

# Survival berdasarkan gender
survival_gender = df.groupby('Sex')['Survived'].mean()

print(survival_gender)

# ---------------------------------------------------------
# Interpretasi:
# Penumpang wanita memiliki tingkat keselamatan yang jauh
# lebih tinggi dibanding pria.
#
# Hal ini sesuai dengan kebijakan evakuasi Titanic:
# "Women and children first".
# ---------------------------------------------------------

# =========================================================
# TAMBAHAN ANALISIS
# Survival berdasarkan gender dan kelas
# =========================================================

print("\n===== ANALISIS TAMBAHAN =====")

survival_gender_class = df.groupby(
    ['Pclass', 'Sex']
)['Survived'].mean().unstack()

print(survival_gender_class.round(3))

# ---------------------------------------------------------
# Interpretasi:
# Wanita kelas 1 memiliki tingkat keselamatan tertinggi.
# Pria kelas 3 memiliki tingkat keselamatan terendah.
#
# Faktor gender dan kelas sosial sangat mempengaruhi
# peluang keselamatan penumpang Titanic.
# ---------------------------------------------------------

# =========================================================
# SELESAI
# =========================================================

print("\n===== ANALISIS SELESAI =====")

===== DATA TITANIC =====
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8